# Numpy and its functions

In [1]:
import numpy as np

In [2]:
salary = np.random.randint(5,100,9)
salary

array([38, 53, 56, 19, 38, 16, 13, 79, 24])

In [3]:
salary = np.clip(salary,a_min=15,a_max=50)
salary

array([38, 50, 50, 19, 38, 16, 15, 50, 24])

In [4]:
print(np.where(salary<20))
print(np.where(salary>25))
print(np.where(salary==50))
print(np.where(salary<=33))
print(np.where(salary>=15))

(array([3, 5, 6]),)
(array([0, 1, 2, 4, 7]),)
(array([1, 2, 7]),)
(array([3, 5, 6, 8]),)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)


In [5]:
salary[[5,8]]

array([16, 24])

# Reshaping

In [6]:
from numpy.random import randint as ri

In [7]:
a = ri(5,65,15)
a

array([57, 33, 13, 17, 23, 64, 29, 34, 34, 28, 43, 59, 64, 40, 10])

In [8]:
b=a.reshape(3,1,5)
b

array([[[57, 33, 13, 17, 23]],

       [[64, 29, 34, 34, 28]],

       [[43, 59, 64, 40, 10]]])

In [9]:
c = a.reshape(3,5)
c

array([[57, 33, 13, 17, 23],
       [64, 29, 34, 34, 28],
       [43, 59, 64, 40, 10]])

In [10]:
print(c.min())
print(c.max())
print(c.mean())
print(c.std())
print(c.var())

10
64
36.53333333333333
17.250571649143176
297.58222222222224


# Sorting

In [11]:
mat = ri(1,50,16).reshape(4,4)
print('-'*30,'\n',mat)
print('-'*30,'\n', np.sort(mat))
print('-'*30, '\n',np.sort(mat,axis=0))

------------------------------ 
 [[25 20 30 20]
 [22  6 21 37]
 [38 40 42 31]
 [27 29 41 35]]
------------------------------ 
 [[20 20 25 30]
 [ 6 21 22 37]
 [31 38 40 42]
 [27 29 35 41]]
------------------------------ 
 [[22  6 21 20]
 [25 20 30 31]
 [27 29 41 35]
 [38 40 42 37]]


# Index & Slicing

In [12]:
arr=np.arange(26,40)
print(arr)
print(arr[2:10])
print(arr[2:10:2])
print(arr[6:])
print(arr[::-1])
print(arr[[5,6,8]])

[26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[28 29 30 31 32 33 34 35]
[28 30 32 34]
[32 33 34 35 36 37 38 39]
[39 38 37 36 35 34 33 32 31 30 29 28 27 26]
[31 32 34]


In [13]:
mat = [[56,45,85],[15,26,39],[78,59,65]]
mat = np.array(mat)
print(mat)

[[56 45 85]
 [15 26 39]
 [78 59 65]]


In [14]:
print(mat[1])
print(mat[2])

[15 26 39]
[78 59 65]


In [15]:
print(mat[:,2:])

[[85]
 [39]
 [65]]


In [16]:
print(mat[1:2,1:3])

[[26 39]]


In [17]:
print(mat[:,[0,2]])

[[56 85]
 [15 39]
 [78 65]]


In [18]:
print(mat)

[[56 45 85]
 [15 26 39]
 [78 59 65]]


In [19]:
mat[1,2]=100
mat

array([[ 56,  45,  85],
       [ 15,  26, 100],
       [ 78,  59,  65]])

# Subsetting

In [20]:
mat=np.array(ri(50,90,15)).reshape(3,5)
mat

array([[83, 72, 53, 83, 57],
       [56, 53, 82, 68, 53],
       [76, 85, 64, 60, 80]])

In [21]:
print("Greater than 70:",mat[mat>70])

Greater than 70: [83 72 83 82 76 85 80]


In [22]:
print("Lesser than 60:",mat[mat<60])

Lesser than 60: [53 57 56 53 53]


In [23]:
print("idx where equal to 54: ",np.where(mat==54))

idx where equal to 54:  (array([], dtype=int64), array([], dtype=int64))


In [24]:
age=60
np.where(age>70,'retired','working')

array('working', dtype='<U7')

# Universal fucntions

In [25]:
mat1=np.array(ri(10,30,16)).reshape(4,4)
mat2 = np.array(ri(10,30,16)).reshape(4,4)

print("mat1 -->",'\n',mat1)
print("mat2 -->",'\n',mat2)

mat1 --> 
 [[29 26 29 13]
 [17 22 16 21]
 [19 28 27 11]
 [19 18 27 17]]
mat2 --> 
 [[11 20 13 13]
 [22 26 14 14]
 [14 15 19 11]
 [23 13 13 24]]


In [26]:
print(mat1/mat2)

[[2.63636364 1.3        2.23076923 1.        ]
 [0.77272727 0.84615385 1.14285714 1.5       ]
 [1.35714286 1.86666667 1.42105263 1.        ]
 [0.82608696 1.38461538 2.07692308 0.70833333]]


In [27]:
print(4*mat1+2*mat2)

[[138 144 142  78]
 [112 140  92 112]
 [104 142 146  66]
 [122  98 134 116]]


# Broadcasting

In [39]:
arr1= np.zeros((2,2),dtype=int)
arr1

array([[0, 0],
       [0, 0]])

In [28]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
add_rows=np.array([1,2,3,4])
add_rows

array([1, 2, 3, 4])

In [30]:
new_arr = arr + add_rows
new_arr

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [31]:
new_row = np.transpose(add_rows)
new_row

array([1, 2, 3, 4])

In [32]:
test = new_row + arr
test

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

# Array Math

In [34]:
mat1 = np.array(ri(10,30,16)).reshape(4,4)
mat2 = np.array(ri(10,30,16)).reshape(4,4)

print('Matrix1','\n',mat1)
print('Matrix2','\n',mat2)

Matrix1 
 [[11 27 29 19]
 [13 23 27 20]
 [12 11 15 20]
 [18 12 26 14]]
Matrix2 
 [[26 23 26 13]
 [22 21 28 13]
 [27 22 12 18]
 [25 10 24 11]]


In [36]:
print('Square roots of mat1:','\n',np.sqrt(mat1))
print('Square roots of mat2:','\n',np.sqrt(mat2))

Square roots of mat1: 
 [[3.31662479 5.19615242 5.38516481 4.35889894]
 [3.60555128 4.79583152 5.19615242 4.47213595]
 [3.46410162 3.31662479 3.87298335 4.47213595]
 [4.24264069 3.46410162 5.09901951 3.74165739]]
Square roots of mat2: 
 [[5.09901951 4.79583152 5.09901951 3.60555128]
 [4.69041576 4.58257569 5.29150262 3.60555128]
 [5.19615242 4.69041576 3.46410162 4.24264069]
 [5.         3.16227766 4.89897949 3.31662479]]


In [37]:
print('Sqaure of mat1:','\n',np.square(mat1))
print('Sqaure of mat2:','\n',np.square(mat2))

Sqaure of mat1: 
 [[121 729 841 361]
 [169 529 729 400]
 [144 121 225 400]
 [324 144 676 196]]
Sqaure of mat2: 
 [[676 529 676 169]
 [484 441 784 169]
 [729 484 144 324]
 [625 100 576 121]]
