In [1]:
import numpy as np

In [10]:
def find_sqrt(x):
   return np.sqrt(x)

print(find_sqrt(25))
print(find_sqrt(100))
print(find_sqrt(16))
print(find_sqrt(15))
print(find_sqrt([15,26,36]))

5.0
10.0
4.0
3.872983346207417
[3.87298335 5.09901951 6.        ]


In [6]:
def give_min(arr):
  return np.amin(arr)

print(give_min([1,2,3,4,5,6,7,8,9,10]))
print(give_min([10,20,30,40,50,60,70,80,90,100]))

1
10


In [7]:
def give_max(arr):
  return np.amax(arr)

print(give_max([1,2,3,4,5,6,7,8,9,10]))

10


In [11]:
def round_off(x):
  return np.ceil(x)

print(round_off(34.6))
print(round_off(50.1))
print(round_off(find_sqrt(65)))

35.0
51.0
9.0


In [13]:
def give_sum(arr):
  return np.sum(arr)

print(give_sum([1,2,3,4,5,6,7,8,9,10]))
print(round_off(give_sum(find_sqrt([1,2,3,4,5,6,7,8,9,10]))))

55
23.0


In [15]:
arr=np.array([54,64,86])
print(arr)
print(type(arr))
print(len(arr))

[54 64 86]
<class 'numpy.ndarray'>
3


In [23]:
twod_arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print(twod_arr)
print(twod_arr.dtype)
print(twod_arr.ndim)
print(twod_arr.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64
2
(3, 3)


In [24]:
li = [5,84,231,6431]
a=np.array(li)
print(a)
print(type(a))
print(a.dtype)

[   5   84  231 6431]
<class 'numpy.ndarray'>
int64


In [26]:
copy_of_a = np.asarray(a)
print(copy_of_a)
print(type(copy_of_a))
print(copy_of_a.dtype)
print(copy_of_a.ndim)

[   5   84  231 6431]
<class 'numpy.ndarray'>
int64
1


In [27]:
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [28]:
a=np.arange(16.15,52.3,5)
print(a)

[16.15 21.15 26.15 31.15 36.15 41.15 46.15 51.15]


In [29]:
a=np.arange(100,64,-3)
print(a)

[100  97  94  91  88  85  82  79  76  73  70  67]


In [37]:
arr,step = np.linspace(6,45,50,endpoint=True,retstep=True)
print(arr)
print(step)

[ 6.          6.79591837  7.59183673  8.3877551   9.18367347  9.97959184
 10.7755102  11.57142857 12.36734694 13.16326531 13.95918367 14.75510204
 15.55102041 16.34693878 17.14285714 17.93877551 18.73469388 19.53061224
 20.32653061 21.12244898 21.91836735 22.71428571 23.51020408 24.30612245
 25.10204082 25.89795918 26.69387755 27.48979592 28.28571429 29.08163265
 29.87755102 30.67346939 31.46938776 32.26530612 33.06122449 33.85714286
 34.65306122 35.44897959 36.24489796 37.04081633 37.83673469 38.63265306
 39.42857143 40.2244898  41.02040816 41.81632653 42.6122449  43.40816327
 44.20408163 45.        ]
0.7959183673469388


In [39]:
a=np.zeros([4,6])
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [40]:
b = np.ones([4,5])
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
c= 67*np.ones([4,5])
c

array([[67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.]])

In [46]:
mat = np.arange(15).reshape(3,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
print(np.random.rand(2,6))
print(np.random.randn(2,6))
print(np.random.randint(1,100,10))

[[0.49015034 0.98833462 0.14638411 0.02696139 0.3078028  0.08000542]
 [0.05413287 0.701016   0.87017083 0.0574288  0.02648056 0.61636178]]
[[ 1.23573347  0.42835663 -0.16222604  0.89383848 -0.86574671  0.37909359]
 [ 1.11420524  0.150221    0.29062562  0.54578229 -1.09285619 -2.00166907]]
[46 33  7 39 63 60 62 30 32 78]


In [49]:
print(np.random.randint(1000,9999,(5,3)))

[[7425 2531 1110]
 [7768 2516 3455]
 [4965 6006 5168]
 [2801 5472 8922]
 [9424 6074 3751]]


In [52]:
def send_otp(otp):
  print(f"OTP is {otp}")

def create_otp():
  otp = np.random.randint(1000,9999)
  send_otp(otp)
  user_otp = int(input("Enter OTP: "))
  if user_otp == otp:
    print("OTP verified")
  else:
    print("OTP invalid")


create_otp()

OTP is 5838
Enter OTP: 5839
OTP invalid
